#!/usr/bin/bash
mkdir -p ${SDK_DIR}
chmod -R u+wr ${SDK_DIR}
cp ${ODI_HOME}/jdeveloper/external/oracle.external.ucp.jar ${SDK_DIR}
cp ${ODI_HOME}/jdeveloper/ide/extensions/oracle.ide.persistence.jar ${SDK_DIR}
cp ${ODI_HOME}/jdeveloper/external/oracle.external.eclipselinkjaxb.jar ${SDK_DIR}
cp ${ODI_HOME}/jdeveloper/wlserver/lib/wls-classes-for-jdev.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/XmlSchema-1.4.2.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/activation.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/aopalliance.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/bsf.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/commons-codec-1.3.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/commons-discovery-0.4.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/commons-logging-1.2.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/commons-net-3.3.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/commons-vfs-1.0.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/connector.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/cpld.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/enterprise_data_quality.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/hsqldb.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/jakarta-oro-2.0.8.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/javolution.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/jms.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/jython.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/odi-core.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/odi-sap.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/odi-wls-template-gen.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/odihapp_common.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/odihapp_essbase.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/odihapp_planning.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/ogg_jmx_interface.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/oracle.odi-jaxrsri.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/oracle.odi-sdk-jse.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/org.eclipse.jgit_3.6.2.201501210735-r.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/pop3.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/sapjco3.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-aop.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-beans.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-context-support.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-context.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-core.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-expression.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-instrument-tomcat.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-instrument.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-jdbc.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-jms.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-orm.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-oxm.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-struts.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-test.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-tx.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-web.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-webmvc-portlet.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/spring-webmvc.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/svnkit-1.8.3.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/trilead-ssh2-1.0.0-build217.jar ${SDK_DIR}
cp ${ODI_HOME}/odi/sdk/lib/trove.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.ucp.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/javax.persistence.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.idm/identitystore.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.jdbc/ojdbc8.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.jps/jps-api.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.odl/ojdl.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/eclipselink.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/org.eclipse.persistence.jpa.jpql.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/org.eclipse.persistence.jpa.jpql.source.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/org.eclipse.persistence.jpa.modelgen.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/org.eclipse.persistence.jpa.modelgen.source.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/org.eclipse.persistence.nosql.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/org.eclipse.persistence.nosql.source.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/org.eclipse.persistence.oracle.nosql.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/org.eclipse.persistence.oracle.nosql.source.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/org.eclipse.persistence.tools.oracleddl.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/org.eclipse.persistence.tools.oracleddl.source.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/org.apache.maven_3.2.5/lib/commons-lang-2.6.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/thirdparty/bsh-2.0b4.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/thirdparty/commons-collections-3.2.2.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/thirdparty/commons-beanutils-1.9.3.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/thirdparty/jackson-core-2.7.9.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/thirdparty/jackson-databind-2.7.9.1.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/thirdparty/features/bsh.vb4.jar ${SDK_DIR}
cp ${ODI_HOME}/wlserver/modules/com.oracle.weblogic.rac.ucp.jar ${SDK_DIR}
cp ${ODI_HOME}/wlserver/modules/com.oracle.weblogic.persistence.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/oracle.toplink/eclipselink-dbwsutils.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/com.sun.xml.ws.sdo-eclipselink-plugin.jar ${SDK_DIR}
cp ${ODI_HOME}/oracle_common/modules/com.sun.xml.ws.jaxws-eclipselink-plugin.jar ${SDK_DIR}
cp ${ODI_HOME}/wlserver/modules/com.oracle.core.eclipselink.integration.jar ${SDK_DIR}
zip odi-sdk-${VERSION}.zip ${SDK_DIR}