steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/odi:$BRANCH_NAME
  - --cache=true
  - --cache-ttl=48h
  - --context=./
  - --single-snapshot
  id: kaniko-build
- name: 'gcr.io/$PROJECT_ID/odi:$BRANCH_NAME'
  entrypoint: buildSdk.sh
  id: sdk-build
- name: gcr.io/cloud-builders/gsutil
  args:
    - cp
    - odi-sdk-*.zip
    - gs://sdk.redpillanalytics.io/odi
  id: sdk-publish
- name: 'gcr.io/$PROJECT_ID/odi:$BRANCH_NAME'
  id: kaniko-test
timeout: 7200s
