steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/odi:latest
  - --cache=true
  - --cache-ttl=48h
  - --context=./
  - --single-snapshot
  id: kaniko-build
- name: 'gcr.io/$PROJECT_ID/odi:latest'
  id: kaniko-test
timeout: 7200s

